name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: FranzDiebold/github-env-vars-action@v2.3.1
    - name: Set env variable
      run: |
        echo "MY_IMAGE_TAG=v1-${CI_REF_NAME_SLUG}-${CI_SHA_SHORT}" >> "$GITHUB_ENV"

    - name: Print environment variables
      run: env
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$MY_IMAGE_TAG
